### ISSUE TITLE
Asset Attributions

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#2]
When set on a digital asset, the attribution (see `.component__attribution` as an example) appears on the screen at the bottom of a picture and covers some of the content.

Attribution should be:

- moved below the picture
- Text should be aligned to the right
- If possible background should fit the content

**Comment by hardik-sagacity** [comment]
I have changed the position and added background and moved the text to right.
and made background fit content
![NFON_Pedigree_UK_Foundation_Nwho_](https://user-images.githubusercontent.com/77665752/106481762-c7078280-64d2-11eb-9230-99d2c2454d4b.png)
