### ISSUE TITLE
Create "alert" classes

### ISSUE THREAD

**Issue by nfon-christophe** [saga-nfon/adapt-nfon-theme#4]
So to keep inline with DocFX, could we please add what docfx refers to as alert?

See for reference:
- Microsoft Contributor Guide: https://docs.microsoft.com/en-gb/contribute/markdown-reference#alerts-note-tip-important-caution-warning
- DocFX Markdown: https://docs.microsoft.com/en-gb/contribute/markdown-reference#alerts-note-tip-important-caution-warning

We will need all DocFX alerts/notes + 1 specific to NFON:

TIP
NOTE
IMPORTANT
WARNING
CAUTION
+ HINT (NFON specific, not in DocFX)

For the time being, I have implemented the following custom CSS:

```css
.TIP {background-color: #d2f9d2; border-color: #d2f9d2; padding: 15px; border: 1px solid transparent; font-weight: bold;}
.TIP p:first-child::before {vertical-align: middle; top: 1px; display: inline-block; font-family: 'Glyphicons Halflings'; line-height: 1; content: "\e125"; margin-right: 5px; font-weight: normal;}
.NOTE {background-color: #99e0f7; border-color: #99e0f7; padding: 15px; border: 1px solid transparent; font-weight: bold;}
.NOTE p:first-child::before {vertical-align: middle; top: 1px; display: inline-block; font-family: 'Glyphicons Halflings'; line-height: 1; content: "\e086"; margin-right: 5px; font-weight: normal;}
.IMPORTANT {background-color: #99b5c1; border-color: #99b5c1; padding: 15px; border: 1px solid transparent; font-weight: bold;}
.IMPORTANT p:first-child::before {vertical-align: middle; top: 1px; display: inline-block; font-family: 'Glyphicons Halflings'; line-height: 1; content: "\e101"; margin-right: 5px; font-weight: normal;}
```

Note that I have replaced the icon Microsoft is using, as they are not great. I have also used 'Glyphicons Halflings' for the moment.

Ideally the classes should be usable:
- within a component HTML body: We use this by adding a DIV around some of the content (see example below)
- as a class on a text component: it will apply to the whole component

Example for use of DIV in a component HTML body:

```html
<p>As mentioned above, any SIP device can be connected to Cloudya, even devices that have not been certified by NFON. We refer to these as "<strong>Unprovisioned SIP devices</strong>".</p><p>However, Cloudya will be unable to provision these devices and some features will therefore not be available, or accessible to these devices (Hot-desking, access to contact directory, function keys, etc.).</p><div class="IMPORTANT"><p>IMPORTANT</p><p>NFON will also not be able to provide support for such devices or for issues that arise from using them.</p></div>
```

**Comment by nfon-christophe** [comment]
'Glyphicons Halflings' or alternative font needs to be added to the theme

**Comment by hardik-sagacity** [comment]
Hello Team I have added the similar markdowns as docfx.

here are the samples.

![Adapt_v5_Presentation_Components](https://user-images.githubusercontent.com/77665752/107878247-3fb90680-6ef7-11eb-8564-6a35920bcb05.png)

**Comment by nfon-christophe** [comment]
The fontawsome icons are not showing properly. See screenshot.

![Screenshot 2021-02-24 192738](https://user-images.githubusercontent.com/54438034/109054931-6e449780-76d6-11eb-862f-ce237cf9260e.png)

**Comment by hardikforall** [comment]
I have updated the font family for these icons. Now it should start working.
 If not please let us know. because sometimes this CSS on CDN for fontawsome is blocked on VPN.

**Comment by hardik-sagacity** [comment]
I have updated the font family for these icons. Now it should start working.
If not please let us know. because sometimes this CSS on CDN for fontawsome is blocked on VPN.

**Comment by nfon-christophe** [comment]
Now working
